# Generated by Django 4.2 on 2023-06-12 09:15

from django.db import migrations

import data_models.models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=data_models.models.LowercaseEmailField(max_length=254, unique=True),
        ),
    ]
