# Generated by Django 4.2.3 on 2023-07-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="prev_password",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
