# Generated by Django 4.2 on 2023-07-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceptionBookImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_date", models.DateField(verbose_name="データ反映日")),
                (
                    "legal_affairs_bureau_request_month",
                    models.DateField(verbose_name="法務局受付月"),
                ),
                (
                    "prefectures",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.prefectures",
                        verbose_name="都道府県ID",
                    ),
                ),
            ],
        ),
    ]
