# Generated by Django 4.2 on 2023-07-26 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0003_receptionbookimport"),
        ("data_models", "0003_user_prev_password"),
    ]

    operations = []
