# Generated by Django 4.2 on 2023-07-31 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0004_merge_20230726_1117"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="プランID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="プランタイプID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="プラン名")),
                ("price", models.IntegerField(verbose_name="プラン料金")),
            ],
        ),
        migrations.CreateModel(
            name="UserPlan",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="プランID",
                    ),
                ),
                ("contract_start_day", models.DateField(verbose_name="契約開始日")),
                ("contract_end_day", models.DateField(verbose_name="契約終了日")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanArea",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="プランエリアID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=256, verbose_name="プラン名")),
                (
                    "city_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.city",
                    ),
                ),
                (
                    "prefecture_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.prefectures",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="data_models.planarea"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="data_models.plantype"
            ),
        ),
    ]
