# Generated by Django 4.2 on 2023-08-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_models",
            "0005_plan_plantype_alter_user_prev_password_userplan_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="プランID"
            ),
        ),
        migrations.AlterField(
            model_name="planarea",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="プランエリアID"
            ),
        ),
        migrations.AlterField(
            model_name="plantype",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="プランタイプID"
            ),
        ),
        migrations.AlterField(
            model_name="userplan",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="プランID"
            ),
        ),
    ]
