# Generated by Django 4.2 on 2023-08-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_models",
            "0005_plan_plantype_alter_user_prev_password_userplan_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="prev_password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
