# Generated by Django 4.2 on 2023-08-06 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_models",
            "0006_alter_plan_id_alter_planarea_id_alter_plantype_id_and_more",
        ),
        ("data_models", "0006_alter_user_prev_password"),
    ]

    operations = []
