# Generated by Django 4.2 on 2023-08-08 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_models",
            "0008_alter_plan_id_alter_planarea_id_alter_plantype_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatereceptionbook",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="realestatereceptionbook",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
