# Generated by Django 4.2 on 2023-08-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_models",
            "0008_alter_plan_id_alter_planarea_id_alter_plantype_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coordinate_type",
                    models.CharField(max_length=256, verbose_name="座標系"),
                ),
                ("polygon", models.JSONField(verbose_name="ポリゴンデータ")),
                ("area", models.FloatField(verbose_name="面積")),
                ("latitude", models.FloatField(verbose_name="代表点緯度")),
                ("longitude", models.FloatField(verbose_name="代表点緯度")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateField(auto_now=True, verbose_name="更新日時")),
            ],
        ),
    ]
