# Generated by Django 4.2 on 2023-08-18 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0009_realestatereceptionbook_created_at_and_more"),
        ("data_models", "0009_registrationmap"),
    ]

    operations = []
