# Generated by Django 4.2 on 2023-08-21 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0010_merge_20230818_1619"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationmap",
            old_name="polygon",
            new_name="geometry",
        ),
    ]
