# Generated by Django 4.2 on 2023-08-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0011_rename_polygon_registrationmap_geometry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaUsePurposeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_purpose_type",
                    models.CharField(max_length=256, verbose_name="土地利用目的コード"),
                ),
                ("name", models.CharField(max_length=256, verbose_name="土地利用目的")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateField(auto_now=True, verbose_name="更新日時")),
            ],
        ),
        migrations.CreateModel(
            name="AreaUsePurpose",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_late", models.FloatField(verbose_name="遮蔽率")),
                ("geometry", models.JSONField(verbose_name="ポリゴンデータ")),
                ("volume_late", models.FloatField(verbose_name="容積率")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateField(auto_now=True, verbose_name="更新日時")),
                (
                    "prefecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.prefectures",
                        verbose_name="都道府県ID",
                    ),
                ),
                (
                    "use_purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.areausepurposetype",
                        verbose_name="土地利用目的コード",
                    ),
                ),
            ],
        ),
    ]
