# Generated by Django 4.2 on 2023-08-22 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0012_areausepurposetype_areausepurpose"),
    ]

    operations = [
        migrations.RenameField(
            model_name="areausepurpose",
            old_name="use_purpose",
            new_name="area_use_purpose",
        ),
        migrations.RenameField(
            model_name="areausepurposetype",
            old_name="use_purpose_type",
            new_name="area_use_purpose_type",
        ),
    ]
