# Generated by Django 4.2 on 2023-08-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_models",
            "0013_rename_use_purpose_areausepurpose_area_use_purpose_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaUsePurposeConditions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conditions", models.JSONField(verbose_name="公開条件")),
                ("miniature", models.IntegerField(verbose_name="公開縮図")),
                ("published_at", models.DateField(verbose_name="公開日時")),
                ("publish_flag", models.IntegerField(verbose_name="公開条件")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateField(auto_now=True, verbose_name="更新日時")),
                (
                    "prefecture_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.prefecturescity",
                        verbose_name="市区町村都道府県ID",
                    ),
                ),
            ],
        ),
    ]
