# Generated by Django 4.2 on 2023-08-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0014_areausepurposeconditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areausepurposeconditions",
            name="published_at",
            field=models.DateField(null=True, verbose_name="公開日時"),
        ),
    ]
