# Generated by Django 4.2 on 2023-08-23 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0015_alter_areausepurposeconditions_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areausepurpose",
            name="prefecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="data_models.prefecturescity",
                verbose_name="市区町村都道府県ID",
            ),
        ),
    ]
