# Generated by Django 4.2 on 2023-08-23 00:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0016_alter_areausepurpose_prefecture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="areausepurpose",
            old_name="prefecture",
            new_name="prefecture_city",
        ),
    ]
