# Generated by Django 4.2 on 2023-08-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0017_rename_prefecture_areausepurpose_prefecture_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areausepurposetype",
            name="area_use_purpose_type",
            field=models.CharField(max_length=256, verbose_name="用途地域分類コード"),
        ),
        migrations.AlterField(
            model_name="areausepurposetype",
            name="name",
            field=models.CharField(max_length=256, verbose_name="用途地域分類"),
        ),
        migrations.DeleteModel(
            name="AreaUsePurpose",
        ),
    ]
