# Generated by Django 4.2 on 2023-08-23 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0018_alter_areausepurposetype_area_use_purpose_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaUsePurpose",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_late", models.FloatField(verbose_name="遮蔽率")),
                ("geometry", models.JSONField(verbose_name="ポリゴンデータ")),
                ("volume_late", models.FloatField(verbose_name="容積率")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateField(auto_now=True, verbose_name="更新日時")),
                (
                    "area_use_purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.areausepurposetype",
                        verbose_name="用途地域分類コード",
                    ),
                ),
                (
                    "area_use_purpose_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.areausepurposeconditions",
                        verbose_name="用途地域公開条件ID",
                    ),
                ),
                (
                    "prefecture_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.prefecturescity",
                        verbose_name="市区町村都道府県ID",
                    ),
                ),
            ],
        ),
    ]
