# Generated by Django 4.2 on 2023-08-24 08:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0022_areausepurposeconditions_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areausepurposeconditions",
            name="conditions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, max_length=10),
                size=5,
                verbose_name="公開条件",
            ),
        ),
    ]
