# Generated by Django 4.2 on 2023-08-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0023_alter_areausepurposeconditions_conditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shozai", models.CharField(max_length=256, verbose_name="所在")),
                ("chiban", models.CharField(max_length=256, verbose_name="地番")),
                (
                    "real_estate_id",
                    models.CharField(max_length=256, null=True, verbose_name="不動産ID"),
                ),
                ("latitude", models.FloatField(verbose_name="代表点緯度")),
                ("longitude", models.FloatField(verbose_name="代表点緯度")),
                (
                    "owner_latest_get_date",
                    models.DateField(null=True, verbose_name="所有者事項最新取得日"),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateField(auto_now=True, verbose_name="更新日時")),
                (
                    "area_use_purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.areausepurpose",
                        verbose_name="用途地域データ",
                    ),
                ),
                (
                    "prefecture_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.prefecturescity",
                        verbose_name="市区町村都道府県ID",
                    ),
                ),
                (
                    "registration_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.registrationmap",
                        verbose_name="法務省登記所備付地図",
                    ),
                ),
            ],
        ),
    ]
