# Generated by Django 4.2 on 2023-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0024_estate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Estate",
            new_name="Land",
        ),
    ]
