# Generated by Django 4.2 on 2023-08-28 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0025_rename_estate_land"),
    ]

    operations = [
        migrations.RenameField(
            model_name="land",
            old_name="shozai",
            new_name="address",
        ),
    ]
