# Generated by Django 4.2 on 2023-08-28 01:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0026_rename_shozai_land_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="land",
            old_name="address",
            new_name="locaiton",
        ),
    ]
