# Generated by Django 4.2 on 2023-08-28 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0027_rename_address_land_locaiton"),
    ]

    operations = [
        migrations.RenameField(
            model_name="land",
            old_name="locaiton",
            new_name="location",
        ),
    ]
