# Generated by Django 4.2 on 2023-08-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0028_rename_locaiton_land_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areausepurpose",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="areausepurpose",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="areausepurposeconditions",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="areausepurposeconditions",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="areausepurposetype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="areausepurposetype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="land",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="land",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="registrationmap",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="registrationmap",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
