# Generated by Django 4.2 on 2023-08-30 01:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0029_alter_areausepurpose_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areausepurposeconditions",
            name="conditions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True), size=5, verbose_name="公開条件"
            ),
        ),
    ]
