# Generated by Django 4.2 on 2023-08-30 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0030_alter_areausepurposeconditions_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="area_use_purpose",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data_models.areausepurpose",
                verbose_name="用途地域データ",
            ),
        ),
    ]
