# Generated by Django 4.2 on 2023-08-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0031_alter_land_area_use_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="land",
            name="area_use_purpose",
        ),
        migrations.CreateModel(
            name="LandAreaUsePurpose",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_use_purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.areausepurpose",
                        verbose_name="用途地域データ",
                    ),
                ),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.land",
                        verbose_name="土地データ",
                    ),
                ),
            ],
        ),
    ]
