# Generated by Django 4.2 on 2023-08-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0033_landareausepurpose_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landareausepurpose",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="landareausepurpose",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
