# Generated by Django 4.2 on 2023-08-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0034_alter_landareausepurpose_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="areausepurpose",
            old_name="area_use_purpose",
            new_name="area_use_purpose_type",
        ),
        migrations.AlterField(
            model_name="land",
            name="longitude",
            field=models.FloatField(verbose_name="代表点経度"),
        ),
    ]
