# Generated by Django 4.2 on 2023-09-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_models",
            "0035_rename_area_use_purpose_areausepurpose_area_use_purpose_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestatereceptionbook",
            name="chiban",
            field=models.CharField(blank=True, max_length=256, verbose_name="地番"),
        ),
    ]
