# Generated by Django 4.2 on 2023-09-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0036_alter_realestatereceptionbook_chiban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestatereceptionbook",
            name="kaoku_number",
            field=models.CharField(blank=True, max_length=256, verbose_name="家屋番号"),
        ),
    ]
