# Generated by Django 4.2 on 2023-09-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0039_buildingareausepurpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="registration_map",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="data_models.registrationmap",
                verbose_name="法務省登記所備付地図",
            ),
        ),
    ]
