# Generated by Django 4.2 on 2023-09-08 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0040_alter_land_registration_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicLandPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=256, verbose_name="所在"),
                ),
                (
                    "chiban",
                    models.CharField(blank=True, max_length=256, verbose_name="地番"),
                ),
                ("land_price", models.IntegerField(null=True, verbose_name="公示価格")),
                ("year", models.IntegerField(null=True, verbose_name="年度")),
                (
                    "jukyo_hyoji",
                    models.CharField(blank=True, max_length=100, verbose_name="住居表示"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, default=None, null=True, verbose_name="代表点緯度"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, default=None, null=True, verbose_name="代表点経度"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prefectures",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.prefectures",
                        verbose_name="都道府県コード",
                    ),
                ),
            ],
        ),
    ]
