# Generated by Django 4.2 on 2023-09-08 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_models", "0041_publiclandprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkLandPriceToLand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.land",
                        verbose_name="土地ID",
                    ),
                ),
                (
                    "public_land_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_models.publiclandprice",
                        verbose_name="公示価格ID",
                    ),
                ),
            ],
        ),
    ]
